# # Reff: http://wiki.ros.org/costmap_2d
# global_frame: map
# robot_base_frame: base_link
# footprint: [[0.14, 0.14], [0.14, -0.14], [-0.14, -0.14], [-0.14, 0.14]]
# rolling_window: true

# inflation_radius: 0.5
# cost_scaling_factor: 4.0

# track_unknown_space: true
# observation_sources: scan
# scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}


# 这些是两张 costmap 共享的通用参数；不要在这里写 global_frame / robot_base_frame
footprint: [[0.14, 0.14], [0.14, -0.14], [-0.14, -0.14], [-0.14, 0.14]]
inflation_radius: 0.5
cost_scaling_factor: 4.0
track_unknown_space: false

# 使用点云作为障碍源
observation_sources: depth_points
depth_points:
  data_type: PointCloud2           # 关键：点云
  topic: /sensor_scan              # 你的实际话题
  marking: true
  clearing: true
  sensor_frame: sensor_at_scan
  # 建议给高度门限（把地面噪声滤掉，按你场景调整）
  min_obstacle_height: 0.05        # m
  max_obstacle_height: 1.5         # m
  # 如果希望在这里覆盖量程，可加（否则用全局/局部 costmap 里的 obstacle/raytrace_range）
  # obstacle_range: 2.5
  # raytrace_range: 3.0
  # 不要写 sensor_frame，默认用消息 header.frame_id 最稳
  # expected_update_rate: 0.0      # 可选，>0 会对更新频率做健康检查（单位：s）
