# # # Reff: http://wiki.ros.org/costmap_2d
# # global_costmap:
# #     update_frequency: 2.0
# #     publish_frequency: 1.0

# #     obstacle_range: 5.0
# #     raytrace_range: 5.0
# #     static_map: true

# #     width: 15.0
# #     height: 15.0


# # Reff: http://wiki.ros.org/costmap_2d
# global_costmap:
#     global_frame: map              # 全局参考坐标系
#     robot_base_frame: vehicle      # 用你 TF 里实际存在的 vehicle

#     update_frequency: 2.0
#     publish_frequency: 1.0
#     transform_tolerance: 0.5

#     obstacle_range: 5.0
#     raytrace_range: 5.0
#     static_map: true

#     width: 15.0
#     height: 15.0
#     resolution: 0.05               # 建议显式写出分辨率（和地图一致）

#     plugins:
#       - {name: static_layer,    type: "costmap_2d::StaticLayer"}
#       - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

#     inflation_layer:
#       inflation_radius: 0.5
#       cost_scaling_factor: 3.0

# Reff: http://wiki.ros.org/costmap_2d
global_costmap:
  global_frame: map            # 全局坐标
  robot_base_frame: vehicle    # 你 TF 里真实存在的底座帧

  update_frequency: 2.0
  publish_frequency: 1.0
  transform_tolerance: 0.5

  # 全局图通常只叠静态地图 + 膨胀层；不需要障碍层
  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # 可选：如果你确实在发 /map_updates（你有这个话题）
  static_layer:
    map_topic: /map
    subscribe_to_updates: true   # 想用 /map_updates 就开；否则删掉这两行

  # 可选：显示写出尺寸/分辨率（仅在 rolling_window=false 时生效；静态层以地图为准）
  width: 15.0
  height: 15.0
  resolution: 0.05

  inflation_layer:
    inflation_radius: 0.5
    cost_scaling_factor: 3.0

