# # # Reff: http://wiki.ros.org/costmap_2d
# # local_costmap:
# #     update_frequency: 5.0
# #     publish_frequency: 2.0

# #     obstacle_range: 2.5
# #     raytrace_range: 2.5
# #     static_map: false

# #     width: 2.5
# #     height: 2.5
# #     resolution: 0.02


# # Reff: http://wiki.ros.org/costmap_2d
# local_costmap:
#     # 关键：现在没有 odom，就先用 map；底座帧用你 TF 里存在的 vehicle
#     global_frame: map
#     robot_base_frame: vehicle

#     update_frequency: 5.0
#     publish_frequency: 2.0
#     transform_tolerance: 0.5

#     obstacle_range: 2.5
#     raytrace_range: 2.5
#     static_map: false

#     # 局部图需要滚动窗口
#     rolling_window: true
#     width: 2.5
#     height: 2.5
#     resolution: 0.02

#     # 插件（与全局图呼应：局部图一般用障碍层+膨胀层）
#     plugins:
#       - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
#       - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

#     # 如果你没有在 costmap_common.yaml 里设置膨胀参数，这里也可以给一个默认：
#     inflation_layer:
#       inflation_radius: 0.5
#       cost_scaling_factor: 3.0

# Reff: http://wiki.ros.org/costmap_2d
local_costmap:
  # 你现在没有稳定的 odom，就先用 map；以后有 odom 再改成 odom 更合适
  global_frame: map
  robot_base_frame: vehicle
  track_unknown_space: false

  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5

  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.02   # 若负载大/抖动多，可改 0.03~0.05

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # 膨胀参数（若已在 costmap_common.yaml 里配置过，也可以删掉这里的重复）
  inflation_layer:
    inflation_radius: 0.5
    cost_scaling_factor: 3.0

