# # Reff: http://wiki.ros.org/navfn
# base_global_planner : navfn/NavfnROS


NavfnROS:
  allow_unknown: true        # 探索必须允许未知
  default_tolerance: 0.3     # 目标在障碍/未知边上时的就近落点半径
  visualize_potential: false
  planner_window_x: 0.0
  planner_window_y: 0.0
