TrajectoryPlannerROS:
  # 运动模型
  holonomic_robot: false            # 差速驱动通常 false
  max_vel_x: 0.5
  min_vel_x: 0.05
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.3
  acc_lim_x: 1.0
  acc_lim_theta: 2.0
  escape_vel: -0.2                  # 卡住时可尝试后退

  # 采样与仿真
  sim_time: 2.0                     # 轨迹前向仿真时长 (s)
  sim_granularity: 0.025            # 轨迹离散间隔 (m)
  angular_sim_granularity: 0.025
  vx_samples: 6
  vtheta_samples: 20

  # 目标容忍
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  # 代价权重（路径/目标/障碍）
  path_distance_bias: 32.0          # 贴近全局路径
  goal_distance_bias: 24.0          # 朝向目标
  occdist_scale: 0.02               # 避障权重（越大越避障）

  # 前瞻与安全
  heading_lookahead: 0.325
  heading_scoring: false            # 若开启，会更重视朝向目标的朝向
  heading_scoring_timestep: 0.1
  dwa: false                        # 设为 true 会近似 DWA 行为；传统 TP 置 false
  meter_scoring: true               # 代价按米计

  # 振荡/裁剪
  prune_plan: true
  oscillation_reset_dist: 0.5

  # 障碍膨胀相关（通常在 costmap 里设，这里给出常用值以便你统一风格）
  # footprint 参数放在 costmap_common_params.yaml 中
